### ISSUE TITLE
Panic: runtime error

### ISSUE THREAD

**Issue by gounthar** [updatecli/updatecli#1770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get a 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xaa3e39]

goroutine 1 [running]:
github.com/updatecli/updatecli/pkg/core/reports.(*Action).UpdatePipelineURL(0xc0021ca080)
        /home/runner/work/updatecli/updatecli/pkg/core/reports/action.go:115 +0x79
github.com/updatecli/updatecli/pkg/core/pipeline.(*Pipeline).RunActions(0xc00061a0c0)
        /home/runner/work/updatecli/updatecli/pkg/core/pipeline/actions.go:135 +0x1525
github.com/updatecli/updatecli/pkg/core/pipeline.(*Pipeline).Run(0xc00061a0c0)
        /home/runner/work/updatecli/updatecli/pkg/core/pipeline/main.go:236 +0x3ba
github.com/updatecli/updatecli/pkg/core/engine.(*Engine).Run(0x50f7ea0)
        /home/runner/work/updatecli/updatecli/pkg/core/engine/run.go:16 +0xf8
github.com/updatecli/updatecli/cmd.run({0x2eff911?, 0x0?})
        /home/runner/work/updatecli/updatecli/cmd/root.go:101 +0xa65
github.com/updatecli/updatecli/cmd.glob..func1(0xc0001c6c00?, {0xc0008c1090?, 0x0?, 0x5?})
        /home/runner/work/updatecli/updatecli/cmd/apply.go:47 +0x26d
github.com/spf13/cobra.(*Command).execute(0x50b3480, {0xc0008c1040, 0x5, 0x5})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x50b2900)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/updatecli/updatecli/cmd.Execute()
        /home/runner/work/updatecli/updatecli/cmd/root.go:49 +0x5b
main.main()
        /home/runner/work/updatecli/updatecli/main.go:8 +0xf
```

when using this command:

` updatecli apply --config updatecli/updatecli.d/jenkins-lts.yaml --values updatecli/values.github-action.yaml --experimental`
on the  https://github.com/gounthar/jenkins.io.git repo (`branch lts-and-bom`).

It does not happen when I remove `experimental`.

### Expected Behavior

A pull request created.

### Steps To Reproduce

Under WSL2/Debian, with updatecli version, run the command ` updatecli apply --config updatecli/updatecli.d/jenkins-lts.yaml --values updatecli/values.github-action.yaml --experimental` in  the https://github.com/gounthar/jenkins.io.git repo

### Environment

```markdown
- OS: PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
- updatecli: 0.66.0
```

**Comment by gounthar** [comment]
Thank you so much. 🤗
